version: '3.7'
services:
  whispywyser-gpu:
    container_name: whispywyser
    image: ghcr.io/cociweb/whispywyser_amd64-cuda:latest
    ports:
      - 10300:10300
    volumes:
      - whispywyser_data:/data
    restart: always
    command: >
      --uri 'tcp://0.0.0.0:10300'
      --data-dir '/data'
      --model-dir '/data/models'
      --model 'openai/whisper-large-v3
      --model-type 'transformers'
      --device 'cuda'
      --compute-type 'float32'
      --language 'en'
      --beam-size '5'
      --initial-prompt "This is a home automation system, controlling and querying devices. I can interpret the following actions: Controlling lights and switches: turning on, off, dimming. Starting and stopping devices. Pausing and stopping media playback. Adjusting settings for water heaters, heating, and air conditioning modes and temperatures. Managing irrigation zones and external weather conditions such as temperature, humidity, precipitation amount, wind strength, and direction.""
    environment:
      - HF_TOKEN="hf_yourverysecretaccesstoken"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  whispywyser-cpu:
    container_name: whispywyser
    image: ghcr.io/cociweb/whispywyser_amd64-cpu:latest
    ports:
      - 10300:10300
    volumes:
      - whispywyser_data:/data
    restart: always
    command: >
      --uri 'tcp://0.0.0.0:10300'
      --data-dir '/data'
      --model-dir '/data/models'
      --model 'systran/faster-whisper-base.en'
      --model-type 'ct2'
      --device 'cpu'
      --cpu-threads '0'
      --compute-type 'default'
      --language 'en'
      --beam-size '5'
      --initial-prompt "This is a home automation system, controlling and querying devices. I can interpret the following actions: Controlling lights and switches: turning on, off, dimming. Starting and stopping devices. Pausing and stopping media playback. Adjusting settings for water heaters, heating, and air conditioning modes and temperatures. Managing irrigation zones and external weather conditions such as temperature, humidity, precipitation amount, wind strength, and direction.""
    environment:
#      - OMP_NUM_THREADS=4 # Uncomment if you want to set the number of cpu-threads, other than default 0
      - HF_TOKEN="hf_yourverysecretaccesstoken"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8096M


volumes:
  whispywyser_data: