name: Build and Publish

on:
## Trigger on pushes to main and tags with vX.X.X, and allow manual dispatch, we will publish images, otherwise just build.
  push:
    branches:
      - '**'
    tags: [ 'v*.*.*' ]
  workflow_dispatch:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            baseimage: nvidia/cuda:12.9.0-cudnn-runtime-ubuntu22.04@sha256:1ba89fe6504e31d41bd7a6070fe8ec56d6cce1cfafa01b0a0c4e5305de072351
            base_type: cuda
          - arch: aarch64
            platform: linux/arm64/v8
            baseimage: nvidia/cuda:12.9.0-cudnn-runtime-ubuntu22.04@sha256:a9765b6702832fc3a4190cb459f692a19b933e176f57a6d8000807c6b940bdab
            base_type: cuda
          - arch: aarch64
            platform: linux/arm64/v8
            baseimage: python:3.12.9-slim-bookworm@sha256:40011d5cf225eb43b650ec158d4a59ca3110e6566ddfd3f506824db6153761cf
            base_type: cpu
          - arch: amd64
            platform: linux/amd64
            baseimage: python:3.12.9-slim-bookworm@sha256:32432ed74044491491c7bd9e11f78d25f7053218ca39af3d5bb038280610086b
            base_type: cpu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Decide push or load
        id: decide
        run: |
          # Default: do not push
          PUSH_IMAGE=false
          if [[ "${{ github.event_name }}" == "push" && ( "${GITHUB_REF}" == refs/heads/main || "${GITHUB_REF}" == refs/tags/v* ) ]] || [[ "${{ github.event_name }}" == "workflow_dispatch" && "${GITHUB_REF}" == refs/heads/main ]]; then
            echo "PUSH_IMAGE=true" >> $GITHUB_ENV
          else
            echo "PUSH_IMAGE=false" >> $GITHUB_ENV
          fi

      - name: Set lowercase repository name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and (optionally) push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: WhispyWyser/Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            BASEIMAGE=${{ matrix.baseimage }}
            ARCHITECTURE=${{ matrix.arch }}
            BASE_TYPE=${{ matrix.base_type }}
          tags: |
            ghcr.io/${{ env.REPO_LC }}_${{ matrix.arch }}-${{ matrix.base_type }}
            ghcr.io/${{ env.REPO_LC }}_${{ matrix.arch }}-${{ matrix.base_type }}:latest
          push: ${{ env.PUSH_IMAGE == 'true' }}
