name: Build and Publish

on:
## Trigger on pushes to main and tags with vX.X.X, and allow manual dispatch, we will publish images, otherwise just build.
  push:
    branches:
      - '**'
      - '!main'
    tags:
      - 'v*.*.*'
      - 'V*.*.*'
      - '*.*.*'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'


jobs:
  decision:
    runs-on: ubuntu-latest
    steps:
      - name: Decide push or load
        id: decide
        run: |
          # Default: do not push
          PUSH_IMAGE=false
          if [[ "${{ github.event_name }}" == "push" && ( "${{ github.ref_name }}" == "refs/heads/main" || "${{ github.ref_type }}" ==  "tag" ) ]] || [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.ref_name }}" == "refs/heads/main" ]] || [[ "${{ github.event_name }}" == "pull_request" && "${{ github.ref_name }}" == "refs/heads/main" ]]; then
            echo "PUSH_IMAGE=true" >> $GITHUB_ENV
          else
            echo "PUSH_IMAGE=false" >> $GITHUB_ENV
          fi
  deploy:
    needs: decision
    runs-on: ubuntu-latest
    steps:
        - name: Bump version
          id: bump
          uses: callowayproject/bump-my-version@master
          env:
            BUMPVERSION_TAG: "true"
          with:
            args: ${{ inputs.bump-type }}
            github-token: ${{ secrets.GITHUB_TOKEN }}

        - name: Check
          if: steps.bump.outputs.bumped == 'true'
          run: |
            echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"

    
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
              python-version: "3.x"
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install setuptools wheel twine build
        - name: Build
          run: python -m build

<<<<<<< HEAD
=======
        - name: Bump version
          if: env.PUSH_IMAGE == 'true'
          id: bump
          uses: callowayproject/bump-my-version@master
          env:
            BUMPVERSION_TAG: "true"
          with:
            args: --destination pyproject.toml ${{ inputs.bump-type }}
            github-token: ${{ secrets.GITHUB_TOKEN }}

        - name: Check
          if: steps.bump.outputs.bumped == 'true'
          run: |
            echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"

>>>>>>> 92a94ec (Update build.yaml)
        - name: Publish
          if: env.PUSH_IMAGE == 'true'
          env:
              TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
              TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          run: twine upload dist/*

  build:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            baseimage: nvidia/cuda:12.9.0-cudnn-runtime-ubuntu22.04
            base_type: cuda
          - arch: aarch64
            platform: linux/arm64
            baseimage: nvidia/cuda:12.9.0-cudnn-runtime-ubuntu22.04
            base_type: cuda
          - arch: aarch64
            platform: linux/arm64/v8
            baseimage: python:3.11-slim-bookworm
            base_type: cpu
          - arch: amd64
            platform: linux/amd64
            baseimage: python:3.11-slim-bookworm
            base_type: cpu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image name
        run: |
          REPO="${{ github.repository }}"
          REPO_LC="${REPO,,}"
          echo "REPO_LC=${REPO_LC}" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/${REPO_LC}_${{ matrix.arch }}-${{ matrix.base_type }}" >> $GITHUB_ENV

      - name: Build and (optionally) push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            BASEIMAGE=${{ matrix.baseimage }}
            ARCHITECTURE=${{ matrix.arch }}
            BASE_TYPE=${{ matrix.base_type }}
          tags: |
            ${{ env.IMAGE_NAME }}
            ${{ env.IMAGE_NAME }}:latest
            ${{ github.event_name == 'push' && (github.ref_type == 'tag') && format('{0}:{1}', env.IMAGE_NAME, github.ref_name) || '' }}
          push: ${{ env.PUSH_IMAGE == 'true' }}
